{% set name = "cling" %}
{% set version = "0.6" %}
{% set sha256 = "c72efd121f65afb0bf2744d4871fd9758f265a750ce921fdef767c8ab9a0fa36" %}
{% set build_number = 0 %}
{% set clang_version = [5, 0, 0] %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/root-project/cling/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}
  patches:
    # Export all symbols on windows to generate import library
    - patches/0001-Export-all-symbols-on-windows.patch
    # Do not build Jupyter kernel - use xeus-cling instead
    - patches/0001-remove-jupyter.patch
    - patches/0027-conda-packaging.patch
    # Prevent setting sysroot include directory on OS Xd
    - patches/0001-Drop-compile-time-sysroot.patch

build:
  number: {{ build_number }}
  skip: True  # [win and vc<14]
  run_exports:
    - {{ pin_subpackage(name, max_pin='x.x') }}

requirements:
  build:
    - cmake
    - ninja  # [win]
    - {{ compiler('cxx') }}
  host:
    - llvmdev {{ clang_version[0] }}
    - clangdev {{ clang_version|join('.') }}
    - clang_variant * cling_v{{ version }}
    - zlib
    # Strong run exports from clangxx_osx-64 don't pin libcxx.
    # Cling does require the same version of libcxx to be used.
    - {{ pin_compatible('libcxx', exact=True) }}  # [osx]
  run:
    # We really depend on the host compiler at runtime:
    #  - the host compiler STL is one to be used.
    #  - it is used by cling's runtime compatibility check.
    - {{ compiler('cxx') }}  # [linux]
    # Strong run exports from clangxx_osx-64 don't pin libcxx.
    # Cling does require the same version of libcxx to be used.
    - {{ pin_compatible('libcxx', exact=True) }}  # [osx]
    - clangdev {{ clang_version|join('.') }}
    - clang_variant * cling_v{{ version }}

test:
  commands:
    - test -f $PREFIX/bin/cling  # [unix]
    - if exist %LIBRARY_PREFIX%\\bin\\libcling.dll (exit 0) else (exit 1)  # [win]
    - if exist %LIBRARY_PREFIX%\\lib\\libcling.lib (exit 0) else (exit 1)  # [win]
    - cling '2+3; 0'
    - cling '#include <vector>'

about:
  dev_url: https://github.com/root-project/cling
  doc_url: https://root.cern.ch/cling
  home: https://root.cern.ch/cling
  license: UI/NCSAOSL
  license_family: BSD
  license_file: LICENSE.TXT
  summary: Cling - The Interactive C++ Interpreter
  description: Cling is an interactive C++ interpreter, built on top of Clang and
    LLVM compiler infrastructure. Cling realizes the read-eval-print loop (REPL)
    concept, in order to leverage rapid application development. Implemented as
    a small extension to LLVM and Clang, the interpreter reuses their strengths
    such as the praised concise and expressive compiler diagnostics.

extra:
  recipe-maintainers:
    - SylvainCorlay
    - JohanMabille
    - gouarin
    - chrisburr
