appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: gH7d1CA7PGUejvxsYZDnu6SZQn8RzJ8GDgsb+KCBgFH/alMNTxBhRP/kM+Mq6oEAeQkbWRyHoD/UZxM4dx1zrEr/GUQ1vKLUW0/tDsWUpjU8AbvZpFsaiNXKO3fPpEta9OKTkucKqt7QFAqsL8bixCySs7um3zS5O6XpkEc+CpViHJ6KHHuyyAYK0rqDLKBjadf44+psIo5+ghuSd53PeTb1rzQvxIJifvM8KtO0R7TIFNkM7MYE4Egn0QkfDbGcgeHiOQ+gidO2bAYtgQYlprwxeMACHxgFSecF6cLghfb5podF2x/5cZXpO7W2mE4wNqXxMXmVEcl57WRCeZg0VOHSxVkgh521sYqOggCcleE83kYeGwOTlorKbO7CQnfqiWv39GoR2JFJovLylxEVucqwmRJ6esBLwoXd4U13qvKPanhPIXTAmctJpAs+uhXmFx9PJwgM/AOABOJq31e8LHemfCjRquFcBsT5HmOGylkcM5NDeb4MLVWpyMZHNvx+xIovlv36SeDV/VvDXIcLV+skjhDVB26UFcQzIRMsCKgMbhfNme1XA56rusfNJKBrvfxglmXCuCYAGOLqxQrrKdZXCkyc/dCTow6N3o75/hitJnn7zw3jbSJBsSIotfNwgDQ/vn+QneH2946iSz+2pjC3eoxSF33aV0k8b0zHp9s=}
conda_forge_output_validation: true
